src/Button.stories.tsx
src/Button.tsx

- You can make it a link by mentioning the `href` props.
- For links you can add a specific target
- Button now has `onClick` props

Add actions to button

---

src/Text.stories.tsx
src/Text.tsx
src/helpers.ts
src/index.ts
src/tokens.ts

- Add new breakpoints token
- Add new breakpoints helpers
- Apply breakpoints to the Text component

Breakpoints

---

src/IntegrationImage/Connector.tsx
src/IntegrationImage/IntegrationImage.stories.tsx
src/IntegrationImage/IntegrationImage.tsx
src/IntegrationImage/index.ts
src/Placeholder/Placeholder.tsx
src/button/Button.stories.tsx
src/icon/index.tsx
src/index.ts

Import `IntegrationImage` from https://5be26744d2f6250024a9117d-nuaekskjtk.chromatic.com/?path=/story/integrations-catalog-layout-integrationimage--with-connector&args=accent:!hex(ffd000);name:coco;hideDropShadow:true

Integration image

---

src/CustomerStoryHero/CustomerStoryHero.stories.tsx
src/CustomerStoryHero/CustomerStoryHero.tsx
src/CustomerStoryHero/index.tsx
src/_helpers/helpers.ts

Similar to [`CommunityHero`](https://github.com/storybookjs/frontpage/blob/main/src/components/screens/CommunityScreen/CommunityHero.tsx) in `frontpage` and in use on [the Storybook Get Involved page](https://storybook.js.org/community/), but simpler and tweaked a bit.
Also adds some comments to `_helpers` to give breakpoints `px/rem` context.

Adds CustomerStoryHero component

---

src/SectionLede/SectionLede.stories.tsx
src/SectionLede/SectionLede.tsx
src/SectionLede/index.tsx

Pulled in from components-marketing and updated for new design needs

Adds SectionLede component

---

src/index.ts

Fixes exports from #20 & #21

---

src/CustomerStoryHero/CustomerStoryHero.tsx
src/SectionLede/SectionLede.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.8.1--canary.24.9d9af97.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.8.1--canary.24.9d9af97.0
yarn add @chromaui/tetra@1.8.1--canary.24.9d9af97.0
```
</details>

Fixes TS errors in SectionLede & CustomerStoryHero

---

src/CustomerStoryHero/CustomerStoryHero.stories.tsx
src/CustomerStoryHero/CustomerStoryHero.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.8.2--canary.25.c9529b8.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.8.2--canary.25.c9529b8.0
yarn add @chromaui/tetra@1.8.2--canary.25.c9529b8.0
```
</details>

Removes errant min-width from CustomerStoryHero

---

src/Button/Button.tsx
src/Header/Header.stories.tsx
src/Header/Header.tsx
src/Header/NavDesktopLink.tsx
src/Header/NavDesktopTrigger.tsx
src/Header/context.tsx
src/Header/types.ts

<details>
<summary>📦 Published PR as canary version: <code>1.9.4--canary.29.dada02e.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.9.4--canary.29.dada02e.0
yarn add @chromaui/tetra@1.9.4--canary.29.dada02e.0
```
</details>

Improve active state

---

src/Header/NavDesktopContent.tsx
src/Header/NavDesktopItem.tsx
src/Header/NavMobileSection.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.10.1--canary.32.0055b08.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.10.1--canary.32.0055b08.0
yarn add @chromaui/tetra@1.10.1--canary.32.0055b08.0
```
</details>

Fix subheading color

---

src/Header/Header.stories.tsx
src/Header/NavDesktopContent.tsx
src/Header/NavDesktopLink.tsx
src/Header/NavDesktopTrigger.tsx
src/Header/data-chromatic-v1.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.10.3--canary.34.c827589.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.10.3--canary.34.c827589.0
yarn add @chromaui/tetra@1.10.3--canary.34.c827589.0
```
</details>

Fixes header

---

src/Header/Header.stories.tsx
src/_tokens/tokens.ts

<details>
<summary>📦 Published PR as canary version: <code>1.10.6--canary.37.60be53c.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.10.6--canary.37.60be53c.0
yarn add @chromaui/tetra@1.10.6--canary.37.60be53c.0
```
</details>

Update MD breakpoint

---

package.json
src/Header/Header.stories.tsx
src/Header/Header.tsx
src/Header/NavDesktop.tsx
src/Header/NavDesktopTrigger.tsx
src/Header/NavMobile.tsx
src/Header/styles.ts
src/Icon/icon.stories.tsx
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>1.10.10--canary.42.1c0ef13.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.10.10--canary.42.1c0ef13.0
yarn add @chromaui/tetra@1.10.10--canary.42.1c0ef13.0
```
</details>

Header improvements

---

package.json
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>1.10.11--canary.44.9f27e09.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.10.11--canary.44.9f27e09.0
yarn add @chromaui/tetra@1.10.11--canary.44.9f27e09.0
```
</details>

Move addon to dev dependencies

---

.storybook/preview.tsx
src/Text/Text.stories.tsx
src/_docs/intro.mdx
src/_docs/typography.mdx
src/_localComponents/TypographyHelper/TypographyHelper.stories.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.11.2--canary.58.360b738.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.11.2--canary.58.360b738.0
yarn add @chromaui/tetra@1.11.2--canary.58.360b738.0
```
</details>

Reshuffle things a little bit

---

src/Testimonial/Testimonial.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.14.2--canary.63.184a59b.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.14.2--canary.63.184a59b.0
yarn add @chromaui/tetra@1.14.2--canary.63.184a59b.0
```
</details>

remove max-width on logo when not in compact mode

---

src/_helpers/typography.ts

<details>
<summary>📦 Published PR as canary version: <code>1.15.2--canary.66.895fb56.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.15.2--canary.66.895fb56.0
yarn add @chromaui/tetra@1.15.2--canary.66.895fb56.0
```
</details>

fix heading36 line height

---

src/Testimonial/Testimonial.stories.tsx
src/Testimonial/Testimonial.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.15.3--canary.67.cd0e48f.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.15.3--canary.67.cd0e48f.0
yarn add @chromaui/tetra@1.15.3--canary.67.cd0e48f.0
```
</details>

fix testimonal logo spacing and responsive styles

---

src/Container/Container.stories.tsx
src/Footer/data.tsx
src/Footer/types.ts
src/Header/Header.stories.tsx
src/Link/Link.stories.tsx
src/Link/Link.tsx
src/Stack/Stack.stories.tsx
src/Stack/Stack.tsx
src/_localHelpers/responsiveBlock.ts

* Fix `linkWrapper` forwarding for footer links
* use camelCase for CSS properties that are returned by `BlockWithOption`
* Document `VStack` and `HStack` components
* Document `align` and `justify` props for Stack components
<details>
<summary>📦 Published PR as canary version: <code>1.15.5--canary.69.3b25923.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.15.5--canary.69.3b25923.0
yarn add @chromaui/tetra@1.15.5--canary.69.3b25923.0
```
</details>

Misc fixes

---

src/Footer/Footer.stories.tsx
src/Footer/Footer.tsx
src/Footer/data.tsx
src/Footer/types.ts

<details>
<summary>📦 Published PR as canary version: <code>1.15.6--canary.70.c3fd3b9.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.15.6--canary.70.c3fd3b9.0
yarn add @chromaui/tetra@1.15.6--canary.70.c3fd3b9.0
```
</details>

Add home link to logo in the footer

---

src/SubNav/SubNav.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.15.11--canary.76.410dba3.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.15.11--canary.76.410dba3.0
yarn add @chromaui/tetra@1.15.11--canary.76.410dba3.0
```
</details>

subnav: remove background color change on hover

---

src/NavDropdownMenu/NavDropdownTrigger.tsx
src/SubNav/SubNav.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.15.12--canary.77.fdf7202.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.15.12--canary.77.fdf7202.0
yarn add @chromaui/tetra@1.15.12--canary.77.fdf7202.0
```
</details>

adjust subnav dropdown trigger sizing

---

src/index.ts

Adds 🪗 Accordion export to index, but for real this time

---

src/Testimonial/Testimonial.stories.tsx
src/Testimonial/Testimonial.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.16.2--canary.85.edf3d06.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.16.2--canary.85.edf3d06.0
yarn add @chromaui/tetra@1.16.2--canary.85.edf3d06.0
```
</details>

Adds `text-wrap: balanced` option to Testimonial

---

src/Button/Button.tsx
src/Link/Link.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.16.4--canary.87.27f383e.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.16.4--canary.87.27f383e.0
yarn add @chromaui/tetra@1.16.4--canary.87.27f383e.0
```
</details>

use ReactNode as children type in button and link

---

src/Footer/Footer.tsx
src/Logo/Logo.tsx

<details>
<summary>📦 Published PR as canary version: <code>1.16.9--canary.92.ea651f5.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.16.9--canary.92.ea651f5.0
yarn add @chromaui/tetra@1.16.9--canary.92.ea651f5.0
```
</details>

Adds alt attribute to footer logo

---

package.json
yarn.lock

<details>
<summary>📦 Published PR as canary version: <code>1.16.10--canary.95.8a1d0d1.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.16.10--canary.95.8a1d0d1.0
yarn add @chromaui/tetra@1.16.10--canary.95.8a1d0d1.0
```
</details>

Align sb theming

---

src/_tokens/tokens.ts

<details>
<summary>📦 Published PR as canary version: <code>1.16.11--canary.93.9bcedb4.0</code></summary>
<br />
```bash
npm install @chromaui/tetra@1.16.11--canary.93.9bcedb4.0
yarn add @chromaui/tetra@1.16.11--canary.93.9bcedb4.0
```
</details>

add font family css variable

---

README.md
src/Container/Container.tsx
src/_docs/typography.mdx

<details>
<summary>📦 Published PR as canary version: <code>1.18.1--canary.100.f3c3171.0</code></summary>
<br />
```bash
npm install @chromatic-com/tetra@1.18.1--canary.100.f3c3171.0
yarn add @chromatic-com/tetra@1.18.1--canary.100.f3c3171.0
```
</details>

fix max-width for full width container

---

package.json

<details>
<summary>📦 Published PR as canary version: <code>1.18.1--canary.102.723614c.0</code></summary>
<br />
```bash
npm install @chromatic-com/tetra@1.18.1--canary.102.723614c.0
yarn add @chromatic-com/tetra@1.18.1--canary.102.723614c.0
```
</details>

add author to package json to fix release

---

package.json

<details>
<summary>📦 Published PR as canary version: <code>2.0.1--canary.109.8575a0f.0</code></summary>
<br />
```bash
npm install @chromatic-com/tetra@2.0.1--canary.109.8575a0f.0
yarn add @chromatic-com/tetra@2.0.1--canary.109.8575a0f.0
```
</details>

configure auto to use release brances

---

src/Header/data.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.4--canary.114.9aab842.0</code></summary>
<br />
```bash
npm install @chromatic-com/tetra@2.0.4--canary.114.9aab842.0
yarn add @chromatic-com/tetra@2.0.4--canary.114.9aab842.0
```
</details>

Change features to platform on mobile nav

---

src/Header/Header.tsx
src/Header/NavDesktop.tsx
src/Header/data.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.5--canary.115.6b9b6af.0</code></summary>
<br />
```bash
npm install @chromatic-com/tetra@2.0.5--canary.115.6b9b6af.0
yarn add @chromatic-com/tetra@2.0.5--canary.115.6b9b6af.0
```
</details>

fix position of platforms dropdown in fullwidth mode

---

src/Header/Header.stories.tsx
src/Header/Header.tsx
src/Header/types.ts

<details>
<summary>📦 Published PR as canary version: <code>2.0.6--canary.116.5927d98.0</code></summary>
<br />
```bash
npm install @chromatic-com/tetra@2.0.6--canary.116.5927d98.0
yarn add @chromatic-com/tetra@2.0.6--canary.116.5927d98.0
```
</details>

add sticky styles for signup button

---

src/Footer/data.tsx

<details>
<summary>📦 Published PR as canary version: <code>2.0.8--canary.119.09dbba3.0</code></summary>
<br />
```bash
npm install @chromatic-com/tetra@2.0.8--canary.119.09dbba3.0
yarn add @chromatic-com/tetra@2.0.8--canary.119.09dbba3.0
```
</details>

update bluesky link
